### ISSUE TITLE
Complete research on Geolocation

### ISSUE THREAD

**Issue by josephhilby** [Apres-Ski/.github#13]
Resources:
---

- https://www.pluralsight.com/guides/how-to-use-geolocation-call-in-reactjs

To Dos:
---

- [ ] Find a tool / API to use
- [ ] Test out in a sandbox repo to make sure it works
- [ ] If it passes, then decide the `user flow` for if a user `decides to use their location` or `wants to input a peak`

**Comment by tricia-holmes** [comment]
We decided we are going to either `randomize` or `hardcode` a user's location. Closing this ticket.
