### ISSUE TITLE
Create Wireframes

### ISSUE THREAD

**Issue by josephhilby** [Apres-Ski/.github#15]
To-Do:
- [x] Create Wireframes in Excalidraw
- [x] Pin link in # apresski-capstone

**Comment by tricia-holmes** [comment]
If we are going to hardcode a user's location and/or have a demo user, we would need to update our `login` and `filtering` sections for the wireframe. @MattWalterTX @Nagel29

**Comment by MattWalterTX** [comment]
Yes, Great Catch! Since its a demo, should we replace the login/ sign up with a landing that says something like "DEMO - Please choose a user" then we could list a button for each? Just a thought that could be a simple fix (but i'm not married to it)

**Comment by tricia-holmes** [comment]
Here is the link to the wireframes - https://triciaholmes.notion.site/Apr-s-Ski-Design-Wiki-5b7323435534441a9b2610182191dc28
